name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  docker-lint:
    uses: finleyfamily/workflows/.github/workflows/docker.lint.yml@master
  docker-build:
    needs:
      - docker-lint
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      pull-requests: read
    uses: finleyfamily/workflows/.github/workflows/docker.build.yml@master
    with:
      push-image: false
  spellcheck:
    uses: finleyfamily/workflows/.github/workflows/spellcheck.yml@master
