name: pull_request.closed

on:
  pull_request:
    types: [closed]

jobs:
  purge-images:
    name: Purge Images
    runs-on: ubuntu-latest
    steps:
      - name: Get ID of PR tagged image
        uses: castlabs/get-package-version-id-action@v2.2
        id: version
        with:
          version: pr-${{ github.event.pull_request.number }}
      - name: Delete PR tag
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          package-version-ids: ${{ steps.versions.outputs.ids }}
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          delete-only-untagged-versions: true
          package-type: container
