name: Release

on:
  release:
    types:
      - published

jobs:
  docker:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      pull-requests: read
    uses: finleyfamily/workflows/.github/workflows/docker.build.yml@master
